import 'dart:async';
import 'dart:ui';

import 'package:flutte_template/util/locale/localization.dart';
import 'package:flutter/foundation.dart' show SynchronousFuture;
import 'package:flutter/material.dart';

/*
 * This should be generated by an icapps translation script
 */
class LocalizationDelegate extends LocalizationsDelegate<Localization> {
  const LocalizationDelegate();

  static const LocalizationDelegate delegate = LocalizationDelegate();

  @override
  bool isSupported(Locale locale) => ['nl', 'en', 'fr'].contains(locale.languageCode);

  @override
  Future<Localization> load(Locale locale) => SynchronousFuture<Localization>(Localization(locale));

  @override
  bool shouldReload(LocalizationDelegate old) => false;
}
