##################################################################################
#####                                TODO                                    #####
##################################################################################
Todo:
  path: webservice/todo/
  properties:
    id: int?
    title: String
    completed: bool

##################################################################################
#####                                REMOTE CONFIG                           #####
##################################################################################

LocalizedMessage:
  path: data/remote_config
  properties:
    en: String?