targets:
  $default:
    builders:
      drift_dev:
        options:
          generate_connect_constructor: true
      # Should be removed in the future
      retrofit_generator|retrofit:
        enabled: true
        options:
          nullsafety: true