// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_template/test/viewmodel/splash/splash_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter/material.dart' as _i4;
import 'package:flutter_template/navigator/onboarding_navigator.dart' as _i5;
import 'package:flutter_template/repository/remote_config/remote_config_repository.dart'
    as _i6;
import 'package:flutter_template/repository/shared_prefs/local/local_storage.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LocalStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorage extends _i1.Mock implements _i2.LocalStorage {
  MockLocalStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> checkForNewInstallation() => (super.noSuchMethod(
        Invocation.method(
          #checkForNewInstallation,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateThemeMode(_i4.ThemeMode? themeMode) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateThemeMode,
          [themeMode],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateHasAnalyticsPermission(bool? permissionGranted) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateHasAnalyticsPermission,
          [permissionGranted],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [OnboardingNavigator].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnboardingNavigator extends _i1.Mock
    implements _i5.OnboardingNavigator {
  MockOnboardingNavigator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> goToNextScreen() => (super.noSuchMethod(
        Invocation.method(
          #goToNextScreen,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [RemoteConfigRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteConfigRepository extends _i1.Mock
    implements _i6.RemoteConfigRepository {
  MockRemoteConfigRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> refreshRemoteConfig() => (super.noSuchMethod(
        Invocation.method(
          #refreshRemoteConfig,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  String? getOptionalValue(String? key) =>
      (super.noSuchMethod(Invocation.method(
        #getOptionalValue,
        [key],
      )) as String?);

  @override
  String? getOptionalString(String? key) =>
      (super.noSuchMethod(Invocation.method(
        #getOptionalString,
        [key],
      )) as String?);

  @override
  int? getOptionalInt(String? key) => (super.noSuchMethod(Invocation.method(
        #getOptionalInt,
        [key],
      )) as int?);

  @override
  bool? getOptionalBool(String? key) => (super.noSuchMethod(Invocation.method(
        #getOptionalBool,
        [key],
      )) as bool?);

  @override
  double? getOptionalDouble(String? key) =>
      (super.noSuchMethod(Invocation.method(
        #getOptionalDouble,
        [key],
      )) as double?);

  @override
  Map<T, R> getCustomObjectMap<T, R>(
    String? key,
    R Function(Map<String, dynamic>)? fromJson,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCustomObjectMap,
          [
            key,
            fromJson,
          ],
        ),
        returnValue: <T, R>{},
      ) as Map<T, R>);

  @override
  List<T> getCustomObjectList<T>(
    String? key,
    T Function(Map<String, dynamic>)? fromJson,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCustomObjectList,
          [
            key,
            fromJson,
          ],
        ),
        returnValue: <T>[],
      ) as List<T>);
}
